package entidades;
// Generated 12-09-2016 05:39:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Abono generated by hbm2java
 */
public class Abono  implements java.io.Serializable {


     private Integer idAbono;
     private Cliente cliente;
     private Date fechaAbono;
     private int saldoAbono;
     private int montoAbono;

    public Abono() {
    }

    public Abono(Cliente cliente, Date fechaAbono, int saldoAbono, int montoAbono) {
       this.cliente = cliente;
       this.fechaAbono = fechaAbono;
       this.saldoAbono = saldoAbono;
       this.montoAbono = montoAbono;
    }
   
    public Integer getIdAbono() {
        return this.idAbono;
    }
    
    public void setIdAbono(Integer idAbono) {
        this.idAbono = idAbono;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFechaAbono() {
        return this.fechaAbono;
    }
    
    public void setFechaAbono(Date fechaAbono) {
        this.fechaAbono = fechaAbono;
    }
    public int getSaldoAbono() {
        return this.saldoAbono;
    }
    
    public void setSaldoAbono(int saldoAbono) {
        this.saldoAbono = saldoAbono;
    }
    public int getMontoAbono() {
        return this.montoAbono;
    }
    
    public void setMontoAbono(int montoAbono) {
        this.montoAbono = montoAbono;
    }




}


