package entidades;
// Generated 04-09-2016 05:14:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String nombreProducto;
     private int cantidadProducto;
     private int precioProducto;
     private boolean estadoProducto;
     private Set ventas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String nombreProducto, int cantidadProducto, int precioProducto, boolean estadoProducto) {
        this.nombreProducto = nombreProducto;
        this.cantidadProducto = cantidadProducto;
        this.precioProducto = precioProducto;
        this.estadoProducto = estadoProducto;
    }
    public Producto(String nombreProducto, int cantidadProducto, int precioProducto, boolean estadoProducto, Set ventas) {
       this.nombreProducto = nombreProducto;
       this.cantidadProducto = cantidadProducto;
       this.precioProducto = precioProducto;
       this.estadoProducto = estadoProducto;
       this.ventas = ventas;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public int getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(int cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
    public int getPrecioProducto() {
        return this.precioProducto;
    }
    
    public void setPrecioProducto(int precioProducto) {
        this.precioProducto = precioProducto;
    }
    public boolean isEstadoProducto() {
        return this.estadoProducto;
    }
    
    public void setEstadoProducto(boolean estadoProducto) {
        this.estadoProducto = estadoProducto;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


