package entidades;
// Generated 04-09-2016 05:14:23 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idUsuario;
     private String passUsuario;

    public Usuario() {
    }

    public Usuario(String idUsuario, String passUsuario) {
       this.idUsuario = idUsuario;
       this.passUsuario = passUsuario;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getPassUsuario() {
        return this.passUsuario;
    }
    
    public void setPassUsuario(String passUsuario) {
        this.passUsuario = passUsuario;
    }




}


