package entidades;
// Generated 24-08-2016 03:13:47 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String passUsuario;

    public Usuario() {
    }

    public Usuario(String passUsuario) {
       this.passUsuario = passUsuario;
    }
   
    public String getPassUsuario() {
        return this.passUsuario;
    }
    
    public void setPassUsuario(String passUsuario) {
        this.passUsuario = passUsuario;
    }




}


