package entidades;
// Generated 23-08-2016 22:12:21 by Hibernate Tools 4.3.1



/**
 * VentaId generated by hbm2java
 */
public class VentaId  implements java.io.Serializable {


     private int idVenta;
     private int idCliente;
     private int idProducto;

    public VentaId() {
    }

    public VentaId(int idVenta, int idCliente, int idProducto) {
       this.idVenta = idVenta;
       this.idCliente = idCliente;
       this.idProducto = idProducto;
    }
   
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VentaId) ) return false;
		 VentaId castOther = ( VentaId ) other; 
         
		 return (this.getIdVenta()==castOther.getIdVenta())
 && (this.getIdCliente()==castOther.getIdCliente())
 && (this.getIdProducto()==castOther.getIdProducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVenta();
         result = 37 * result + this.getIdCliente();
         result = 37 * result + this.getIdProducto();
         return result;
   }   


}


