package entidades;
// Generated 12-09-2016 05:39:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private Cliente cliente;
     private Producto producto;
     private int montoVenta;
     private Date fechaVenta;
     private int cantidadVenta;

    public Venta() {
    }

    public Venta(Cliente cliente, Producto producto, int montoVenta, Date fechaVenta, int cantidadVenta) {
       this.cliente = cliente;
       this.producto = producto;
       this.montoVenta = montoVenta;
       this.fechaVenta = fechaVenta;
       this.cantidadVenta = cantidadVenta;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public int getMontoVenta() {
        return this.montoVenta;
    }
    
    public void setMontoVenta(int montoVenta) {
        this.montoVenta = montoVenta;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public int getCantidadVenta() {
        return this.cantidadVenta;
    }
    
    public void setCantidadVenta(int cantidadVenta) {
        this.cantidadVenta = cantidadVenta;
    }




}


