package entidades;
// Generated 24-08-2016 0:50:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private VentaId id;
     private Cliente cliente;
     private Producto producto;
     private Integer montoVenta;
     private Date fechaVenta;
     private Integer cantidadVenta;

    public Venta() {
    }

	
    public Venta(VentaId id, Cliente cliente, Producto producto) {
        this.id = id;
        this.cliente = cliente;
        this.producto = producto;
    }
    public Venta(VentaId id, Cliente cliente, Producto producto, Integer montoVenta, Date fechaVenta, Integer cantidadVenta) {
       this.id = id;
       this.cliente = cliente;
       this.producto = producto;
       this.montoVenta = montoVenta;
       this.fechaVenta = fechaVenta;
       this.cantidadVenta = cantidadVenta;
    }
   
    public VentaId getId() {
        return this.id;
    }
    
    public void setId(VentaId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Integer getMontoVenta() {
        return this.montoVenta;
    }
    
    public void setMontoVenta(Integer montoVenta) {
        this.montoVenta = montoVenta;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Integer getCantidadVenta() {
        return this.cantidadVenta;
    }
    
    public void setCantidadVenta(Integer cantidadVenta) {
        this.cantidadVenta = cantidadVenta;
    }




}


